# Generated by Django 5.2.7 on 2026-08-27 05:11

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    Role.objects.get_or_create(name="admin")
    Role.objects.get_or_create(name="collaborator")


def remove_default_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    Role.objects.filter(
        name__in=["admin", "collaborator"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(
            create_default_roles,
            remove_default_roles,
        ),
    ]
